<?php

namespace ContainerXnhMxRX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ITzgLeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ITzg_le' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ITzg_le'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'genero' => ['privates', '.errored..service_locator.ITzg_le.App\\Entity\\Genero', NULL, 'Cannot autowire service ".service_locator.ITzg_le": it needs an instance of "App\\Entity\\Genero" but this type has been excluded in "config/services.yaml".'],
        ], [
            'genero' => 'App\\Entity\\Genero',
        ]);
    }
}
