<?php

namespace ContainerXnhMxRX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8jq8HP8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8jq8HP8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8jq8HP8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'titulo' => ['privates', '.errored..service_locator.8jq8HP8.App\\Entity\\Titulo', NULL, 'Cannot autowire service ".service_locator.8jq8HP8": it needs an instance of "App\\Entity\\Titulo" but this type has been excluded in "config/services.yaml".'],
        ], [
            'titulo' => 'App\\Entity\\Titulo',
        ]);
    }
}
