<?php

namespace ContainerXnhMxRX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4yiYN9XService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4yiYN9X' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4yiYN9X'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'docente' => ['privates', '.errored..service_locator.4yiYN9X.App\\Entity\\Docente', NULL, 'Cannot autowire service ".service_locator.4yiYN9X": it needs an instance of "App\\Entity\\Docente" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'docente' => 'App\\Entity\\Docente',
            'entityManager' => '?',
        ]);
    }
}
