<?php

namespace ContainerXnhMxRX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FJ2V678Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fJ2V678' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fJ2V678'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'institucion' => ['privates', '.errored..service_locator.fJ2V678.App\\Entity\\Institucion', NULL, 'Cannot autowire service ".service_locator.fJ2V678": it needs an instance of "App\\Entity\\Institucion" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'institucion' => 'App\\Entity\\Institucion',
        ]);
    }
}
