<?php

namespace ContainerXnhMxRX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZvAPsAUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zvAPsAU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zvAPsAU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'docente' => ['privates', '.errored..service_locator.zvAPsAU.App\\Entity\\Docente', NULL, 'Cannot autowire service ".service_locator.zvAPsAU": it needs an instance of "App\\Entity\\Docente" but this type has been excluded in "config/services.yaml".'],
        ], [
            'docente' => 'App\\Entity\\Docente',
        ]);
    }
}
