<?php

namespace ContainerXnhMxRX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NDx9wIYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NDx9wIY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NDx9wIY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'genero' => ['privates', '.errored..service_locator.NDx9wIY.App\\Entity\\Genero', NULL, 'Cannot autowire service ".service_locator.NDx9wIY": it needs an instance of "App\\Entity\\Genero" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'genero' => 'App\\Entity\\Genero',
        ]);
    }
}
