<?php

namespace ContainerXnhMxRX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1Lwwy4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1_lwwy4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1_lwwy4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'persona' => ['privates', '.errored..service_locator.1_lwwy4.App\\Entity\\Persona', NULL, 'Cannot autowire service ".service_locator.1_lwwy4": it needs an instance of "App\\Entity\\Persona" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'persona' => 'App\\Entity\\Persona',
        ]);
    }
}
