<?php

namespace ContainerXnhMxRX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGeneroService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ITzg_le.App\Entity\Genero' shared service.
     *
     * @return \App\Entity\Genero
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ITzg_le": it needs an instance of "App\\Entity\\Genero" but this type has been excluded in "config/services.yaml".');
    }
}
