<?php

namespace ContainerXnhMxRX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInstitucionTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\InstitucionType' shared autowired service.
     *
     * @return \App\Form\InstitucionType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/InstitucionType.php';

        return $container->privates['App\\Form\\InstitucionType'] = new \App\Form\InstitucionType();
    }
}
