<?php

namespace ContainerXnhMxRX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocalidadService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.QsNpvgy.App\Entity\Localidad' shared service.
     *
     * @return \App\Entity\Localidad
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.QsNpvgy": it needs an instance of "App\\Entity\\Localidad" but this type has been excluded in "config/services.yaml".');
    }
}
