<?php

namespace ContainerXnhMxRX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPersona2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.dV9IGeb.App\Entity\Persona' shared service.
     *
     * @return \App\Entity\Persona
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.dV9IGeb": it needs an instance of "App\\Entity\\Persona" but this type has been excluded in "config/services.yaml".');
    }
}
