<?php

namespace ContainerEVfwbl2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DV9IGebService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dV9IGeb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dV9IGeb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'persona' => ['privates', '.errored..service_locator.dV9IGeb.App\\Entity\\Persona', NULL, 'Cannot autowire service ".service_locator.dV9IGeb": it needs an instance of "App\\Entity\\Persona" but this type has been excluded in "config/services.yaml".'],
        ], [
            'persona' => 'App\\Entity\\Persona',
        ]);
    }
}
