<?php

namespace ContainerEVfwbl2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QW81yqtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qW81yqt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qW81yqt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'provincium' => ['privates', '.errored..service_locator.qW81yqt.App\\Entity\\Provincia', NULL, 'Cannot autowire service ".service_locator.qW81yqt": it needs an instance of "App\\Entity\\Provincia" but this type has been excluded in "config/services.yaml".'],
        ], [
            'provincium' => 'App\\Entity\\Provincia',
        ]);
    }
}
