<?php

namespace ContainerEVfwbl2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QsNpvgyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QsNpvgy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QsNpvgy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'localidad' => ['privates', '.errored..service_locator.QsNpvgy.App\\Entity\\Localidad', NULL, 'Cannot autowire service ".service_locator.QsNpvgy": it needs an instance of "App\\Entity\\Localidad" but this type has been excluded in "config/services.yaml".'],
        ], [
            'localidad' => 'App\\Entity\\Localidad',
        ]);
    }
}
