<?php

namespace ContainerEVfwbl2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VJg4tCVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vJg4tCV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vJg4tCV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'localidad' => ['privates', '.errored..service_locator.vJg4tCV.App\\Entity\\Localidad', NULL, 'Cannot autowire service ".service_locator.vJg4tCV": it needs an instance of "App\\Entity\\Localidad" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'localidad' => 'App\\Entity\\Localidad',
        ]);
    }
}
