<?php

namespace ContainerEVfwbl2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RSYqIfKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rSYqIfK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rSYqIfK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'pai' => ['privates', '.errored..service_locator.rSYqIfK.App\\Entity\\Pais', NULL, 'Cannot autowire service ".service_locator.rSYqIfK": it needs an instance of "App\\Entity\\Pais" but this type has been excluded in "config/services.yaml".'],
        ], [
            'pai' => 'App\\Entity\\Pais',
        ]);
    }
}
