<?php

namespace ContainerEVfwbl2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDocenteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.4yiYN9X.App\Entity\Docente' shared service.
     *
     * @return \App\Entity\Docente
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.4yiYN9X": it needs an instance of "App\\Entity\\Docente" but this type has been excluded in "config/services.yaml".');
    }
}
