<?php

namespace ContainerEVfwbl2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenero2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.NDx9wIY.App\Entity\Genero' shared service.
     *
     * @return \App\Entity\Genero
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.NDx9wIY": it needs an instance of "App\\Entity\\Genero" but this type has been excluded in "config/services.yaml".');
    }
}
