<?php

namespace ContainerEVfwbl2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHabilitante2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.R7FAiB3.App\Entity\Habilitante' shared service.
     *
     * @return \App\Entity\Habilitante
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.R7FAiB3": it needs an instance of "App\\Entity\\Habilitante" but this type has been excluded in "config/services.yaml".');
    }
}
