<?php

namespace ContainerEVfwbl2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInstitucionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.fJ2V678.App\Entity\Institucion' shared service.
     *
     * @return \App\Entity\Institucion
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.fJ2V678": it needs an instance of "App\\Entity\\Institucion" but this type has been excluded in "config/services.yaml".');
    }
}
