<?php

namespace ContainerEVfwbl2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPaisService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.5W2tVo0.App\Entity\Pais' shared service.
     *
     * @return \App\Entity\Pais
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.5W2tVo0": it needs an instance of "App\\Entity\\Pais" but this type has been excluded in "config/services.yaml".');
    }
}
