<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEVfwbl2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEVfwbl2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEVfwbl2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEVfwbl2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEVfwbl2\App_KernelDevDebugContainer([
    'container.build_hash' => 'EVfwbl2',
    'container.build_id' => 'fa23c4f7',
    'container.build_time' => 1691451556,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEVfwbl2');
